---
- name: Add Upstart service
  tags:
    - upstart
  template: src=upstart.conf.j2 dest=/etc/init/{{ service_name }}.conf
  become: yes

- name: Make sure log directory exists with correct permissions
  tags:
    - upstart
  file: >
    state=directory
    path={{ service_log_file | dirname }}
    owner={{ service_user }}
    group={{ service_user }}
    mode=u+rw
  become: yes

- name: Restart service
  tags:
    - upstart
  service: name={{ service_name }} state=restarted
  become: yes
  when: service_restart
